# Generated by Django 5.2 on 2026-09-05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0043_orderattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='jewelry',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='sale_items',
                to='master.jewelry',
            ),
        ),
        migrations.CreateModel(
            name='SoldJewelry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sold_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_jewelry', to='master.customer')),
                ('jewelry', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='sold_record', to='master.jewelry')),
                ('sale_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sold_jewelry_records', to='master.saleitem')),
            ],
        ),
    ]