# Generated by Django 5.2.7 on 2026-09-05 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0048_make_craftsman_payment_fields_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobwork',
            name='customer_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobwork',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobwork',
            name='length',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='jobwork',
            name='return_weight',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='jobwork',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
