# Generated by Django 5.2.7 on 2026-09-05 17:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0049_jobwork_customer_name_jobwork_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobwork',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
