# Generated by Django 5.2.7 on 2026-09-05 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0050_alter_customer_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobwork',
            name='karagir_making',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
