# Generated by Django 5.2.7 on 2026-09-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0051_jobwork_karagir_making'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobwork',
            name='order_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
