# Generated by Django 5.2.7 on 2026-09-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0052_jobwork_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobwork',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('sold', 'Sold')], default='available', max_length=20),
        ),
    ]
