# Generated by Django 5.2.7 on 2026-09-05 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0053_jobwork_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='jobwork',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='master.jobwork'),
        ),
    ]
