# Generated by Django 5.2.7 on 2026-09-17 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0055_khatabookin_khatabookout'),
    ]

    operations = [
        migrations.AddField(
            model_name='craftsmanpayment',
            name='amount_taken',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='craftsmanpayment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
